apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::401601166836:role/udacityclouddevopscapstone-NodeInstanceRole-1NJ30IOA8O0AL
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::401601166836:user/1xshaw
      username: designated_user
      groups:
        - system:masters
